backoffice/urls.py
from django.conf.urls import url
import backoffice.views as views


urlpatterns = [
    url(r'^usuarios/(?P<id>[0-9]+)/editar/$', views.editar_encuesta, name="editar_encuesta"),
    url(r'^usuarios/(?P<id>[0-9]+)/eliminar/$', views.eliminar_encuesta, name="eliminar_encuesta"),
    url(r'^usuarios/(?P<id>[0-9]+)/aprobar/$', views.aprobar_validacion, name="aprobar_validacion"),
    url(r'^usuarios/(?P<id>[0-9]+)/rechazar/$', views.rechazar_validacion, name="rechazar_validacion"),
    url(r'^usuarios/$', views.usuarios, name="usuarios"),
]

pps/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

import validacion.urls
import backoffice.urls

urlpatterns = [
    url(r'^validacion/', include(validacion.urls)),
    url(r'^backoffice/', include(backoffice.urls)),
    url(r'^login/$', auth_views.login, {'template_name': 'validacion/login.html'}, name="login"),
    url(r'^logout/$', auth_views.logout, {'next_page': "/validacion/"}, name="logout"),
    url(r'^admin/', include(admin.site.urls)),
]

validacion/urls.py
from django.conf.urls import url
import validacion.views as views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^preguntas/$', views.preguntas, name="preguntas"),
]

validacion/models.py
from random import shuffle

from django.db import models
from django.conf import settings


class Perfil(models.Model):
    usuario = models.OneToOneField(settings.AUTH_USER_MODEL)
    dni = models.CharField(max_length=8)
    fecha_nacimiento = models.DateField()
    telefono = models.CharField(max_length=10)


class Validacion(models.Model):
    RECHAZADA = "r"
    APROBADA = "a"
    MANUAL = "m"
    EN_CURSO = "e"

    ESTADOS = (
        (RECHAZADA, "Rechazada"),
        (APROBADA, "Aprobada"),
        (MANUAL, "Manual"),
        (EN_CURSO, "En curso"),
    )
    estado = models.CharField(max_length=1, choices=ESTADOS, default=EN_CURSO)
    usuario = models.OneToOneField(Perfil, null=True, blank=True)

    def calcular_resultado(self):
        correctas = self.pregunta_set.filter(estado=Pregunta.CORRECTA).count()
        if correctas == 3:
            self.estado = Validacion.APROBADA
        elif correctas == 2:
            self.estado = Validacion.MANUAL
        else:
            self.estado = Validacion.RECHAZADA
        self.save()


class Pregunta(models.Model):
    SIN_RESPONDER = "s"
    CORRECTA = "c"
    INCORRECTA = "i"

    ESTADOS = (
        (SIN_RESPONDER, "Sin responder"),
        (CORRECTA, "Correcta"),
        (INCORRECTA, "Incorrecta"),
    )

    DOMICILIO = "d"
    EMPRESA = "e"
    VEHICULO = "v"

    TIPOS = (
        (DOMICILIO, "¿Reconocés alguno de estos domicilios, que pueden ser actuales o antiguos?"),
        (EMPRESA, "¿Trabajás o trabajaste para alguna de las siguientes empresas?"),
        (VEHICULO, "¿Tenés o has tenido en el pasado alguno de estos vehículos (automóvil / motocicleta)?"),
    )

    OPCION_NINGUNA = "Ninguna de las anteriores"

    respuesta = models.CharField(max_length=40, default=OPCION_NINGUNA)
    tipo = models.CharField(max_length=1, choices=TIPOS)
    estado = models.CharField(max_length=1, choices=ESTADOS, default=SIN_RESPONDER)
    visto = models.BooleanField(default=False)
    validacion = models.ForeignKey(Validacion, null=True)

    def construir_opciones(self):
        # Traer preguntas existentes del mismo tipo
        respuestas = Pregunta.objects.filter(tipo=self.tipo).exclude(validacion=self.validacion).order_by("?")
        opciones = list(respuestas[:3]) + [self]
        shuffle(opciones)
        return opciones

    def correcta(self):
        self.estado = Pregunta.CORRECTA
        return self.save()

    def incorrecta(self):
        self.estado = Pregunta.INCORRECTA
        return self.save()

    def __str__(self):
        return self.respuesta

backoffice/forms.py
from django import forms
from django.forms.models import modelformset_factory

from validacion.models import Pregunta


class PreguntaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['respuesta'].label = self.instance.get_tipo_display()

    class Meta:
        model = Pregunta
        fields = ['respuesta']

PreguntaFormSet = modelformset_factory(Pregunta, form=PreguntaForm, max_num=3)

validacion/forms.py
from django import forms


class EncuestaForm(forms.Form):
    respuesta = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=[]
    )

    def __init__(self, *args, **kwargs):
        respuestas = kwargs.pop('respuestas', [])
        super().__init__(*args, **kwargs)

        if respuestas:
            resp = [(p, p.respuesta) for p in respuestas]
            self.fields['respuesta'].choices = resp
            self.fields['respuesta'].label = resp[0][0].get_tipo_display()

backoffice/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.admin.views.decorators import staff_member_required

from backoffice.forms import PreguntaFormSet
from validacion.models import Validacion

Usuario = get_user_model()


@staff_member_required
def usuarios(request):
    usuarios = Usuario.objects.filter(is_staff=False).order_by("-id")
    return render(request, "backoffice/usuarios.html", {'usuarios': usuarios})


@staff_member_required
def editar_encuesta(request, id):
    usuario = Usuario.objects.get(id=id)
    validacion = usuario.perfil.validacion
    preguntas = validacion.pregunta_set.all()
    forms = PreguntaFormSet(queryset=preguntas)
    if request.method == "POST":
        formset = PreguntaFormSet(request.POST, queryset=preguntas)
        if formset.is_valid():
            formset.save()
            return redirect("usuarios")

    ctx = {
        'forms': forms,
        'usuario': usuario
    }
    return render(request, "backoffice/encuesta.html", ctx)


@staff_member_required
def eliminar_encuesta(request, id):
    perfil = Usuario.objects.get(id=id).perfil
    perfil.validacion.delete()
    perfil.save()
    Validacion.objects.create(usuario=perfil)
    return redirect("usuarios")


@staff_member_required
def aprobar_validacion(request, id):
    validacion = Usuario.objects.get(id=id).perfil.validacion
    validacion.estado = Validacion.APROBADA
    validacion.save()
    return redirect("usuarios")


@staff_member_required
def rechazar_validacion(request, id):
    validacion = Usuario.objects.get(id=id).perfil.validacion
    validacion.estado = Validacion.RECHAZADA
    validacion.save()
    return redirect("usuarios")

validacion/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from validacion.models import Validacion, Pregunta
from validacion.forms import EncuestaForm


@login_required
def home(request):
    validacion = request.user.perfil.validacion
    return render(request, "validacion/resultado.html", {'estado': validacion.estado})


@login_required
def preguntas(request):
    validacion = request.user.perfil.validacion

    # Si la validacion ya termino redirigir al home
    if validacion.estado != Validacion.EN_CURSO:
        return redirect("home")

    preguntas = validacion.pregunta_set.filter(estado=Pregunta.SIN_RESPONDER)
    if not preguntas.exists():
        # Si se contestaron todas las preguntas calcular el resultado de la validacion
        validacion.calcular_resultado()
        return redirect("home")

    # Traer una pregunta y construirle opciones
    p = preguntas.first()
    opciones = p.construir_opciones()

    if request.method == "POST":
        form = EncuestaForm(request.POST, respuestas=opciones)
        if form.is_valid():
            resp = form.cleaned_data['respuesta']
            if resp == p.respuesta:
                p.correcta()
            else:
                p.incorrecta()
            return redirect("preguntas")
    else:
        # Si no vio la pregunta, marcar como vista
        # Si ya la vio, entonces dejo la encuesta sin responderla, marcar como incorrecta
        if p.visto:
            p.incorrecta()
            return redirect("preguntas")
        p.visto = True
        p.save()

    form = EncuestaForm(respuestas=opciones, initial={'respuesta': opciones[0]})

    return render(request, "validacion/preguntas.html", {'form': form, 'pregunta': p})

pps/templates/backoffice/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Backoffice</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'usuarios' %}">Backoffice</a>
                </div>
                {% if user.is_authenticated %}
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="navbar-brand">Bienvenido, {{ user.username }}</li>
                            <li><a href="{% url 'logout' %}">Cerrar sesión</a></li>
                        </ul>
                    </div>
                {% endif %}
            </div>
        </nav>
        {% block body %}
        {% endblock body %}
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.2.1/backbone-min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/backbone.marionette/2.4.2/backbone.marionette.min.js">
        </script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        {% block js %}
        {% endblock js %}
    </body>
</html>

pps/templates/backoffice/encuesta.html
{% extends "backoffice/base.html" %}

{% block body %}
{% load crispy_forms_tags %}
    <div class="container col-xs-6 col-xs-offset-3">
        <form action="{% url 'editar_encuesta' usuario.id %}" method="post">
            {% csrf_token %}
            {{ forms|crispy }}
            <input type="submit" class="btn btn-success btn-md" value="Guardar"/>
            <a href="{% url 'usuarios' %}" class="btn btn-warning btn-md">Cancelar</a>
        </form>
    </div>
{% endblock body %}

pps/templates/backoffice/usuarios.html
{% extends "backoffice/base.html" %}

{% block body %}
    <div class="container">
        <table class="table table-striped">
            <tr>
                <th>Nombre y apellido</th>
                <th>Email</th>
                <th>DNI</th>
                <th>Estado de validación</th>
                <th>Encuesta</th>
                <th>Verificación</th>
            </tr>
            {% for usuario in usuarios %}
            <tr>
                <td>{{ usuario.get_full_name }}</td>
                <td>{{ usuario.email }}</td>
                <td>{{ usuario.perfil.dni }}</td>
                <td>{{ usuario.perfil.validacion.get_estado_display }}</td>
                <td>
                    <a class="glyphicon glyphicon-pencil" href="{% url 'editar_encuesta' usuario.id %}"></a>
                    <a class="glyphicon glyphicon-trash" href="{% url 'eliminar_encuesta' usuario.id %}"></a>
                </td>
                <td>
                    <a class="glyphicon glyphicon-ok" href="{% url 'aprobar_validacion' usuario.id %}"></a>
                    <a class="glyphicon glyphicon-remove" href="{% url 'rechazar_validacion' usuario.id %}"></a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock body %}

pps/templates/validacion/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Encuesta de validación</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'home' %}">Encuesta</a>
                </div>
                {% if user.is_authenticated %}
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="navbar-brand">Bienvenido, {{ user.username }}</li>
                            <li><a href="{% url 'logout' %}">Cerrar sesión</a></li>
                        </ul>
                    </div>
                {% endif %}
            </div>
        </nav>
        {% block body %}
        {% endblock body %}
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        {% block js %}
        {% endblock js %}
    </body>
</html>

pps/templates/validacion/login.html
{% extends "validacion/base.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="clearfix"></div>
<div class="row container col-xs-4 col-xs-offset-4">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title">Encuesta de validación</div>
        </div>
        <div class="panel-body">
            <form action="{% url 'login' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-primary btn-lg center-block" value="Iniciar sesión"/>
            </form>
        </div>
    </div>
</div>
{% endblock body %}

pps/templates/validacion/preguntas.html
{% extends "validacion/base.html" %}

{% block body %}
{% load crispy_forms_tags %}
{% load staticfiles %}
    <div class="container col-xs-6 col-xs-offset-3">
        <form action="{% url 'preguntas' %}" method="post" data-id="{{ pregunta.id }}">
            {% csrf_token %}
            {{ form|crispy }}
            <p>Tenés <span id="temporizador">20 segundos</span> para responder!</p>
            <input type="submit" class="btn btn-success btn-md" value="Continuar"/>
        </form>
    </div>
{% endblock body %}

{% block js %}
<script src="{% static "js/countdown.min.js" %}"></script>
<script src="{% static "js/temporizador.js" %}"></script>
{% endblock js %}

pps/templates/validacion/resultado.html
{% extends "validacion/base.html" %}
{% load staticfiles %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            {% if estado == 'e' %}
                <h2>Encuesta de validación</h2>
                <p>Para poder otorgarte tu préstamo, necesito verificar tu identidad mediante algunas preguntas sencillas. Presioná el botón Continuar para responderlas.</p>
                <p><a class="btn btn-primary btn-lg" href="{% url 'preguntas' %}" role="button">Continuar</a></p>
            {% else %}
                <h2>Resultado de la validación</h2>
                <p>
                {% if estado == 'a' %}
                    Tu préstamo ha sido aprobado! En las próximas horas vas a recibir la transferencia.
                {% elif estado == 'm' %}
                    Hubo un problema con la verificación. Comunicate conmigo cuanto antes por teléfono o mail para seguir adelante.
                {% elif estado == 'r' %}
                    Lamentablemente tu préstamo fue rechazado. Intentalo de nuevo en 30 días.
                {% endif %}
                </p>
            {% endif %}
        </div>
    </div>
{% endblock body %}